export { default as us } from '../../assets/flags/us.png'
export { default as ca } from '../../assets/flags/ca.png'
// export { default as eu } from '../../assets/flags/eu.png'
export { default as af } from '../../assets/flags/af.png'
export { default as al } from '../../assets/flags/al.png'
export { default as am } from '../../assets/flags/am.png'
export { default as ae } from '../../assets/flags/ae.png'
export { default as ar } from '../../assets/flags/ar.png'
export { default as au } from '../../assets/flags/au.png'
export { default as az } from '../../assets/flags/az.png'
export { default as ba } from '../../assets/flags/ba.png'
export { default as bd } from '../../assets/flags/bd.png'
export { default as bg } from '../../assets/flags/bg.png'
export { default as bh } from '../../assets/flags/bh.png'
