# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'viatorem' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for viatorem
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'viatoremTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'viatorem-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for viatorem-tvOS

  target 'viatorem-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
